CREATE TABLE IF NOT EXISTS Issues (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  summary VARCHAR(100) NOT NULL,
  description VARCHAR(500) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  priority VARCHAR(10) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
